//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hcmuslib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BM_KYTAPCHI
    {
        public int ID_KY { get; set; }
        public string TEN_KY { get; set; }
        public string URL_HINH { get; set; }
        public Nullable<System.DateTime> THOI_GIAN_DANG { get; set; }
        public string LOI_GIOI_THIEU { get; set; }
        public Nullable<int> ANPHAM { get; set; }
    
        public virtual ANPHAM ANPHAM1 { get; set; }
    }
}
