//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hcmuslib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BMNHANDECHINH
    {
        public BMNHANDECHINH()
        {
            this.SACH = new HashSet<SACH>();
        }
    
        public string ID_NHAN_DE { get; set; }
        public string NHAN_DE_CHINH { get; set; }
    
        public virtual ICollection<SACH> SACH { get; set; }
    }
}
