//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hcmuslib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BMSOPHANLOAI
    {
        public BMSOPHANLOAI()
        {
            this.SACH = new HashSet<SACH>();
        }
    
        public string ID_SPL { get; set; }
        public string SO_PHAN_LOAI { get; set; }
    
        public virtual ICollection<SACH> SACH { get; set; }
    }
}
