//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hcmuslib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_DONHANG
    {
        public int ID { get; set; }
        public string ID_DON_HANG { get; set; }
        public string TEN_SAN_PHAM { get; set; }
        public Nullable<int> SO_LUONG { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
    }
}
