//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hcmuslib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DKTAPHUAN
    {
        public int ID { get; set; }
        public string MADG { get; set; }
        public string LOAI { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public string TINHTRANG { get; set; }
    
        public virtual DOCGIA DOCGIA { get; set; }
    }
}
