//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hcmuslib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCGIA
    {
        public DOCGIA()
        {
            this.BOITHUONGTHIETHAI = new HashSet<BOITHUONGTHIETHAI>();
            this.LEARNCOMMONS = new HashSet<LEARNCOMMONS>();
            this.LUUHANHSACH = new HashSet<LUUHANHSACH>();
            this.MUONPHONG = new HashSet<MUONPHONG>();
            this.MUONTAICHO = new HashSet<MUONTAICHO>();
            this.DKTAPHUANs = new HashSet<DKTAPHUAN>();
        }
    
        public string MS_THE { get; set; }
        public string HO_TEN { get; set; }
        public string TINH_TRANG { get; set; }
        public string EMAIL { get; set; }
        public string LOAI_DOC_GIA { get; set; }
        public string IMAGE_URL { get; set; }
    
        public virtual ICollection<BOITHUONGTHIETHAI> BOITHUONGTHIETHAI { get; set; }
        public virtual ICollection<LEARNCOMMONS> LEARNCOMMONS { get; set; }
        public virtual ICollection<LUUHANHSACH> LUUHANHSACH { get; set; }
        public virtual ICollection<MUONPHONG> MUONPHONG { get; set; }
        public virtual ICollection<MUONTAICHO> MUONTAICHO { get; set; }
        public virtual ICollection<DKTAPHUAN> DKTAPHUANs { get; set; }
    }
}
