//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hcmuslib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public string MS_NV { get; set; }
        public string HO_TEN { get; set; }
        public string TINH_TRANG { get; set; }
        public string CHUC_VU { get; set; }
        public string LOAI_NHAN_VIEN { get; set; }
    }
}
