//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hcmuslib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONG
    {
        public PHONG()
        {
            this.MUONPHONG = new HashSet<MUONPHONG>();
        }
    
        public string ID_PHONG { get; set; }
        public string TEN_PHONG { get; set; }
        public string VI_TRI { get; set; }
        public string TINH_TRANG { get; set; }
    
        public virtual ICollection<MUONPHONG> MUONPHONG { get; set; }
    }
}
