//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hcmuslib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THIETBI_DICHVU
    {
        public THIETBI_DICHVU()
        {
            this.LEARNCOMMONS = new HashSet<LEARNCOMMONS>();
        }
    
        public string ID_THIET_BI { get; set; }
        public string TEN_THIET_BI { get; set; }
        public Nullable<System.DateTime> NGAY_NHAP { get; set; }
        public string TINH_TRANG { get; set; }
    
        public virtual ICollection<LEARNCOMMONS> LEARNCOMMONS { get; set; }
    }
}
