//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hcmuslib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_PASSWORD
    {
        public USER_PASSWORD()
        {
            this.DOCGIA = new HashSet<DOCGIA>();
            this.NHANVIEN = new HashSet<NHANVIEN>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
        }
    
        public int ID_USER { get; set; }
        public string USER_NAME { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<int> ROLE { get; set; }
    
        public virtual ICollection<DOCGIA> DOCGIA { get; set; }
        public virtual ICollection<NHANVIEN> NHANVIEN { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
    }
}
